version: "3.9"

services:
  db:
    image: mysql
    volumes:
      - ./data/db:/var/lib/mysql/data
    environment:
      - MYSQL_DB=covidapi
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db